name: Chris Ruppel
permalink: pretty
debug: false
development: false

markdown: redcarpet
redcarpet:
  extensions: ["smart"]

highlighter: pygments
exclude: [README.md, LICENSE.md, package.json, gulpfile.js, Gemfile, Gemfile.lock, node_modules, .bundle, update]

# Content types
# - Set 'output' of any collection to `true` to generate individual pages.
# collections:
#   my_collection:
#     output: false

defaults:
  -
    scope:
      path: "" # all files within the project
    values:
      layout: "default"

# Google Analytics — the dev config unsets this value
ga: 'UA-432773-8'
